# Generated by Django 4.2.7 on 2023-11-05 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coords',
            options={},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={},
        ),
        migrations.AlterModelOptions(
            name='perevaladded',
            options={},
        ),
        migrations.AlterModelOptions(
            name='perevalareas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='perevalimages',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spractivitiestypes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
