# Generated by Django 4.2.7 on 2023-11-05 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0002_alter_coords_options_alter_images_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perevaladded',
            name='coord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pereval.coords'),
        ),
        migrations.AddField(
            model_name='perevalimages',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pereval.images'),
        ),
        migrations.AddField(
            model_name='perevalimages',
            name='pereval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pereval.perevaladded'),
        ),
        migrations.AlterField(
            model_name='perevalareas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
